### ISSUE TITLE
Python/Django?

### ISSUE THREAD

**Issue by bcoover** [AppDirect/service-integration-sdk#121]
Do you have any information about SDK or examples that would help with a Python/Django ISV app also using SAML? Alternately, do you know anyone with expertise in this that could help us integrate our app?

**Comment by EmilDafinov** [comment]
So far we have only implemented the SDK in java. @StephenHeffernan would be a good contact regarding plans for future supported languages

**Comment by StephenHeffernan** [comment]
@bcoover  Right now we are looking for feedback on the SDK and where we can improve it to better help our developer partners in the ecosystem. Adding a second language has definitely been a big ask from several partners. Is Python your preferred language?
