### ISSUE TITLE
Events fetched from the marketplace as XML

### ISSUE THREAD

**Issue by EmilDafinov** [AppDirect/service-integration-sdk#123]
Depending on the configuration of the spring boot app using the SDK, events might be fetched from the AppDirect marketplace as XML instead of JSON. That would cause problems with parsing of the event and it results in null fields in the event handler's input. 

Ensure that the format of the event payload is explicitly stated as JSON when the event is fetched

**Comment by jpboudreault** [comment]
Can we close this ticket?
