### ISSUE TITLE
Update SDK to report usage to MP

### ISSUE THREAD

**Issue by fedesassone** [AppDirect/service-integration-sdk#125]
Update SDK to support the reporting of usage to marketplace using the Marketplace Billing API.

Follow @juan-blasco 's [tech design](https://appdirect.jira.com/wiki/display/PI/Integration+Service+SDK+-+Report+Usage).

**Comment by fedesassone** [comment]
JIRA ticket: [PI-10039](https://appdirect.jira.com/browse/PI-10039)

Associated PR: #124

**Comment by jpboudreault** [comment]
Merged, closing
