### ISSUE TITLE
Deserialization of Subscription Create data model

### ISSUE THREAD

**Issue by andyman021300** [AppDirect/service-integration-sdk#155]
I am trying to use this SDK to support our product listing in an AppDirect marketplace used by a partner.  After loading this SDK into my Spring Boot service, I went to try sending a sample "Subscription Create" to my service.  When I did so, I got this error:

```
exception=JSON parse error: Can not deserialize value of type com.appdirect.sdk.appmarket.events.PricingUnit from String \"EMPLOYEE\": value not one of declared Enum instance names: [PROVIDER, GIGABYTE, PROPERTY, HOST, MEGABYTE, NOT_APPLICABLE, MANAGER, UNIT, USER, ROOM];
```

Basically, it looks like the JSON payload we receive looks (in part) something like this (sorry this is XML formatting, it's what I found at the time I documented this):
```
...
<order>
  <editionCode>123</editionCode>
  <pricingDuration>YEARLY</pricingDuration>
  <item>
     <quantity>1</quantity>
     <unit>EMPLOYEE</unit>
   </item>
   <customAttributes/>
</order>
...
```

The `unit` of `EMPLOYEE` does not seem to be a supported `PricingUnit`, at least according to the [class](https://github.com/AppDirect/service-integration-sdk/blob/master/src/main/java/com/appdirect/sdk/appmarket/events/PricingUnit.java).

So, it looks like possible for some marketplace instantiations to deviate from the standard supported data model (at least according to this SDK).  If I want to use this SDK (which I really do) what is the best way for me to do so?  Should I fork the repo and make the required changes to the data models?  Is the item I noted above (EMPLOYEE as a Pricing Unit) a known bug, or just something that should be expected for some instantiations of the marketplace?

Thank you for the help!

**Comment by hooriak** [comment]
We'll add support for Employee Pricing unit in the next sprint.
