### ISSUE TITLE
Add Default Constructor to User Management event representations

### ISSUE THREAD

**Issue by andyman021300** [AppDirect/service-integration-sdk#160]
For `UserAssignment` and `UserUnassignment` event representations, it would be nice if there were a Lombok `@NoArgsConstructor` annotation included, such that these representations could be deserialized.  This would makes these classes consistent with the Subscription representations.

As it is now, I can serialize these events (for instance, if we were queue these in the event of a failure to process) but we cannot deserialize these events, because of a lack of a default constructor.

Also, `UserUnassignment` uses `@Getter` inconsistently from `UserAssignment`.  If this code is being touched, this may be a good refactor as well.

Thank you.

**Comment by amertkara** [comment]
Hi @andyman021300, it is a good point. I will look into this.

**Comment by hooriak** [comment]
@andyman021300 Can you deserialize using the constructor? Jackson for instance, lets you do that:
http://buraktas.com/convert-objects-to-from-json-by-jackson-example/

**Comment by andyman021300** [comment]
@hooriak I tried out the `@JsonCreator` method but ran into issues with the `EventFlag` field.  I think the open PR out there now looks good.  thanks!

**Comment by amertkara** [comment]
Fixed and released in https://github.com/AppDirect/service-integration-sdk/releases/tag/1.50
